### ISSUE TITLE
Can I open a pull request to add an optional "language" parameter?

### ISSUE THREAD

**Issue by FrancescoBonizzi** [post-op/chatgpt-release#11]
Hi! This action is really helpful, by the way I often need to show release notes to Italian "customers" and I usually write the release notes in Italian. 

My proposal is:
- I add an optional parameter called "two-digits-language-code", the default will be "en" and everything will be as now.
- Add "it" as possible value, I will also add ChatGpt translated prompt for the two prompt tones
- Add a fallback to "en" if the specified language is not available.

What do you think? Can I do it?

Thanks.

**Comment by sklivvz** [comment]
It's a good idea. However, having a "language" parameter that only supports `en` and `it` will confuse most users who don't need English. Let's try this instead. Pass the language as the English name ("Italian"), and we then modify the prompt to say, "Write the message using the ${language} language". That'll work.

**Comment by FrancescoBonizzi** [comment]
Perfect! I forgot that I can ask directly to ChatGpt to translate.

**Comment by FrancescoBonizzi** [comment]
Pulled: https://github.com/post-op/chatgpt-release/pull/16
